### ISSUE TITLE
universal-sentence-encoder url error

### ISSUE THREAD

**Issue by hunter-meloche** [daveshap/REMO_Framework#2]
I think you need either https://tfhub.dev/google/universal-sentence-encoder-large/5 or https://tfhub.dev/google/universal-sentence-encoder/4

What's in the code is https://tfhub.dev/google/universal-sentence-encoder/5 which gives a 404.

**Comment by hunter-meloche** [comment]
This PR takes care of this issue and more so it will work right out of the box https://github.com/daveshap/REMO_Framework/pull/3

**Comment by daveshap** [comment]
Merged! Thanks
